name: Publish mod

on:
  push:
    branches:
      - 'KingsBetterAnimations*'
  pull_request:
    branches:
      - 'KingsBetterAnimations*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      
    - name: List .jar files
      run: ls build/libs
      
    - name: Extract branch name
      id: branch
      run: |
        BRANCH_NAME=$(echo ${{ github.ref }} | sed -n 's|^refs/heads/\(.*\)$|\1|p')
        LAST_PART=$(echo $BRANCH_NAME | awk -F'-' '{print $NF}')
        echo "::set-output name=version::$LAST_PART"
      
    - uses: Kir-Antipov/mc-publish@v3.3
      with:
        version-type: beta
        changelog-file: CHANGES
        version: ${{ steps.branch.outputs.version }}
        files: "build/libs/*.jar !build/libs/*-sources.jar"
        
        modrinth-featured: true
        modrinth-unfeature-mode: subset
        modrinth-dependencies: |
          gedNE4y2@1.0.2-rc1+1.20-fabric(embedded)
          8BmcQJ2H@4.2(embedded)
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
        
        curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
